### ISSUE TITLE
Fix for Office 2016/365 C2R (click-to-run)

### ISSUE THREAD

**Issue by Beej126** [rendezz/Zinkuba#3]
see [this post](https://github.com/miyako/4d-plugin-vbs-outlook) for background...
it seems 2016 tweaked the C2R registry path...
in the fixclick2run.bat provided in releases, remove "\15.0" in all the registry paths
tested on version "20-06" (Build 13001.20266)

**Comment by Beej126** [comment]
closing since this isn't a true issue, just more of an FAQ, maybe consider adding to README

**Comment by itsolver** [comment]
Thanks @Beej126. I ran into this issue as well. Here is the patched fixclick2run.bat that worked for me on Microsoft 365 Apps: https://gist.github.com/itsolver/9a6944e4c88ec5f5300984c8384a93f8#file-fixclick2run-bat

Edit: updated registry patch for 64-bit Office 365.

Without the patch: 

```
ERROR .MessageProcessor.RawToMsgProcessor.ProcessMessage � Failed to process raw [0] into msg : MrMapi failed to process file C:\Users\itsol\AppData\Local\Temp\tmp2850.tmp with exit code 0
Message File Converter
Options specified:
   Input File: C:\Users\itsol\AppData\Local\Temp\tmp2850.tmp
   Output File: C:\Users\itsol\AppData\Local\Temp\439ea288-1478-4e48-bac2-5de42cfef23e.msg
   Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.

System.Exception: MrMapi failed to process file C:\Users\itsol\AppData\Local\Temp\tmp2850.tmp with exit code 0
Message File Converter
Options specified:
   Input File: C:\Users\itsol\AppData\Local\Temp\tmp2850.tmp
   Output File: C:\Users\itsol\AppData\Local\Temp\439ea288-1478-4e48-bac2-5de42cfef23e.msg
   Conversion Type: MIME -> MAPI
MAPI <-> MIME converter not found. Perhaps Outlook is not installed.

   at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ConvertRawToMsg(RawMessageDescriptor message)
   at Zinkuba.MailModule.MessageProcessor.RawToMsgProcessor.ProcessMessage(RawMessageDescriptor message, MessageProcessState state)
```

**Comment by rendezz** [comment]
Thanks, this has been uploaded.

[sig_part_1.jpg]
Darren Hemphill
Chief Technology Officer

Cell: +27 (0) _82 778 0250
Contact Number: +27 (0) 86 111 8324
For More Info Click Here<http://baselineit.co.za/thesig>
A member of the Baseline Group

Email: ***@***.******@***.***/thesig>
[sig_col_3.jpg]
[BaselineWebsite2.png]<http://www.baselineit.co.za/thesig>

[http://baselineit.co.za/thesig/assets/baseline-wired.png]<http://baselinewired.co.za>

[http://baselineit.co.za/thesig/assets/bls-logo-no-text.png]<http://baselinesoftware.co.za>

________________________________
[http://baselineit.co.za/thesig/assets/Microsoft-Silver-Partner.png] [http://baselineit.co.za/thesig/assets/ESET-partner-logo.jpg]  [http://baselineit.co.za/thesig/assets/badjr.png]

On 17 Aug 2022, at 09:22, Angus McLauchlan ***@***.******@***.***>> wrote:



I ran into this issue as well. Here is the patched fixclick2run.bat that worked for me on Microsoft 365 Apps: https://github.com/IT-Solver/Zinkuba/releases/download/release-1.3/fixclick2run.bat<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIT-Solver%2FZinkuba%2Freleases%2Fdownload%2Frelease-1.3%2Ffixclick2run.bat&data=05%7C01%7Cdarren%40baselineit.co.za%7C7de62d551f574a8bfcab08da80214606%7Cde65ad1e3419434486696f8a3f84ecb4%7C0%7C0%7C637963180347753780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vxZzsAJFn4lykR8BsHWHeCa8PM8ww1JlkvwYn9YVKnM%3D&reserved=0>
